

spring:
  application:
    name: mcp-client

  ai:
    mcp:
      client:
        stdio:
          connections:
            boardgamedb:
              command: ${JAVA_HOME}/bin/java
              args:
              - '-jar'
              - '${MCP_SERVER_PATH}/build/libs/mcp-server-0.0.1-SNAPSHOT.jar'
              env:
                SPRING_DOCKER_COMPOSE_FILE: "${MCP_SERVER_PATH}/compose.yaml"

        toolcallback:
          enabled: true
