

spring:


  application:
    name: mcp-filesystem-client



  ai:
    mcp:
      client:
        stdio:

          connections:
            filesystem:  # <1>
              command: 'npx' # <2>
              args: # <3>
                - '-y'
                - '@modelcontextprotocol/server-filesystem'
                - '/Users/habuma/mcp-playground'

        toolcallback:
          enabled: true

